TaiwanGo/Controllers/BookingController.cs
using Microsoft.AspNetCore.Mvc;
using TaiwanGo.Models.Domain;
using TaiwanGo.Models.Wrap;

namespace TaiwanGo.Controllers
{
    public class BookingController : Controller
    {
        public IActionResult List()
        {
            TaiwanGoContext db = new TaiwanGoContext();
            var bookings = db.TBookings
               .Select(b => new CBookingWrap(b))
               .ToList();
            return View(bookings);
        }
    }
}

TaiwanGo/Controllers/StaffController.cs
using Microsoft.AspNetCore.Mvc;
using TaiwanGo.Models.Domain;
using TaiwanGo.Models.Wrap;
using TaiwanGo.ViewModels;

namespace TaiwanGo.Controllers
{
    public class StaffController : Controller
    {
        public IActionResult List(CKeywordViewModel p)
        {
            TaiwanGoContext db = new TaiwanGoContext();
            IEnumerable<TStaff> datas = null;
            if (string.IsNullOrEmpty(p.txtKeyword))
            {
                datas = from s in db.TStaffs
                        select s;
            }
            else
                datas = db.TStaffs.Where(staff => staff.FName.Contains(p.txtKeyword)
                || staff.FEmail.Contains(p.txtKeyword)
                || staff.FPhone.Contains(p.txtKeyword)
                || staff.FRole.Contains(p.txtKeyword));
            // 把 TStaff 轉成 CStaffWrap
            List<CStaffWrap> wraps = datas.Select(s => new CStaffWrap(s)).ToList();
            return View(wraps);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(TStaff s)
        {
            TaiwanGoContext db = new TaiwanGoContext();
            db.TStaffs.Add(s);
            db.SaveChanges();
            return RedirectToAction("List");
        }
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                TaiwanGoContext db = new TaiwanGoContext();
                TStaff delStaff = db.TStaffs.FirstOrDefault(staff => staff.FId == id);
                if (delStaff != null)
                {
                    db.TStaffs.Remove(delStaff);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("List");
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("List"); 
            TaiwanGoContext db = new TaiwanGoContext();
            TStaff delstaff = db.TStaffs.FirstOrDefault(staff => staff.FId == id);
            if (delstaff == null)
                return RedirectToAction("List"); 
            return View(delstaff); 
        }
        [HttpPost]
        public IActionResult Edit(TStaff uiStaff)
        {
            TaiwanGoContext db = new TaiwanGoContext();
            TStaff dbStaff = db.TStaffs.FirstOrDefault(staff => staff.FId == uiStaff.FId);
            if (dbStaff == null)
                return RedirectToAction("List");
            dbStaff.FName = uiStaff.FName;
            dbStaff.FEmail = uiStaff.FEmail;
            dbStaff.FPassword = uiStaff.FPassword;
            dbStaff.FPhone = uiStaff.FPhone;
            dbStaff.FRole = uiStaff.FRole;
            db.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

TaiwanGo/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using TaiwanGo.Models.Domain;
using TaiwanGo.ViewModels;

namespace TaiwanGo.Controllers
{
    public class TicketController : Controller
    {
        public IActionResult List(CKeywordViewModel p)
        {
            TaiwanGoContext db = new TaiwanGoContext();
            IEnumerable<TTicket> datas = null;
            if (string.IsNullOrEmpty(p.txtKeyword))
            {
                datas = from ticket in db.TTickets
                        select ticket;
            }
            else
                datas = db.TTickets.Where(ticket => ticket.FTicketName.Contains(p.txtKeyword));
                
            return View(datas);
        }
    }
}

TaiwanGo/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using TaiwanGo.Models.Domain;
using TaiwanGo.Models.Wrap;
using TaiwanGo.ViewModels;

namespace TaiwanGo.Controllers
{
    public class UserController : Controller
    {
        public IActionResult List(CKeywordViewModel p)
        {
            TaiwanGoContext db = new TaiwanGoContext();
            IEnumerable<TUser> datas = null;
            if (string.IsNullOrEmpty(p.txtKeyword))
            {
                datas = from user in db.TUsers
                        select user;
            }
            else
                datas = db.TUsers.Where(user => user.FName.Contains(p.txtKeyword)
                || user.FEmail.Contains(p.txtKeyword)
                || user.FPhone.Contains(p.txtKeyword));
            // 把 TUser 轉成 CStaffWrap
            List<CUserWrap> wraps = datas.Select(u => new CUserWrap(u)).ToList();
            return View(wraps);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(TUser user)
        {
            TaiwanGoContext db = new TaiwanGoContext();
            db.TUsers.Add(user);
            db.SaveChanges();//更新資料庫
            return RedirectToAction("List");//RedirectToAction方法會重新導向到指定的動作方法
        }
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                TaiwanGoContext db = new TaiwanGoContext();
                TUser deluser = db.TUsers.FirstOrDefault(user => user.FId == id);
                if (deluser != null)
                {
                    db.TUsers.Remove(deluser);//綠框做刪除
                    db.SaveChanges();
                }
            }
            return RedirectToAction("List");
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("List"); // 如果id為null，則重定向到List動作
            TaiwanGoContext db = new TaiwanGoContext();
            TUser deluser = db.TUsers.FirstOrDefault(user => user.FId == id);
            if (deluser == null)
                return RedirectToAction("List"); // 如果找不到對應的用戶，返回List
            return View(deluser); // 傳到畫面用強型別          
        }
        [HttpPost]
        public IActionResult Edit(TUser uiUser)
        {
            TaiwanGoContext db = new TaiwanGoContext();
            TUser dbUser = db.TUsers.FirstOrDefault(user => user.FId == uiUser.FId);
            if (dbUser == null)
                return RedirectToAction("List");
            dbUser.FName = uiUser.FName;
            dbUser.FEmail = uiUser.FEmail;
            dbUser.FPassword = uiUser.FPassword;
            dbUser.FPhone = uiUser.FPhone;
            dbUser.FBirthDate = uiUser.FBirthDate;
            db.SaveChanges();
            return RedirectToAction("List");//利用if後結束語句,少寫else{}的精簡寫法
        }
    }
}

TaiwanGo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - TaiwanGo</title>
	<script type="importmap"></script>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/TaiwanGo.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaiwanGo</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="List">員工管理</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="List">會員管理</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Attraction" asp-action="List">景點資訊</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="List">票券資訊</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="List">訂單管理</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2025 - TaiwanGo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>